# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-09-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskselection', '0005_auto_20181009_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
