# Generated by Django 4.2.7 on 2024-09-19 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskselection", "0008_alter_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["code"]},
        ),
    ]
