# Generated by Django 4.2.7 on 2024-09-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskselection", "0010_alter_task_sv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
