# Generated by Django 4.2.7 on 2024-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskselection", "0011_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
